### ISSUE TITLE
Reason behind this new package

### ISSUE THREAD

**Issue by billouboq** [socketio/socket.io-redis-streams-adapter#1]
Hi,

I would like to know what are the use cased of this package and how it really differ with this one :
https://github.com/socketio/socket.io-redis-adapter/

I saw the explanation below but I'm not sure 100% where it differ appart from the recovery mecanisme

**Comment by darrachequesne** [comment]
Hi! Thanks for opening this :+1: 

The main difference with the existing Redis adapter (which use the [Redis Pub/Sub mechanism](https://redis.io/docs/manual/pubsub/)) is that this adapter will properly handle any temporary disconnection to the Redis server and resume the stream without losing any packets.

**Comment by IPRIT** [comment]
Is there any differences in performance? Do redis streams are better in highload projects?

**Comment by darrachequesne** [comment]
@IPRIT I guess it will depend on your own usage (number of packets per second, size of the packets, ...). As usual, please benchmark against your own usage.

**Comment by chrisandrewcl** [comment]
This [other issue](https://github.com/socketio/socket.io-redis-adapter/issues/420) offers some more context into the why of this package.

**Comment by darrachequesne** [comment]
I think this can now be closed.

For future readers, please check this: https://socket.io/docs/v4/redis-streams-adapter/
