### ISSUE TITLE
emit before disconnectSockets

### ISSUE THREAD

**Issue by SupertigerDev** [socketio/socket.io-redis-streams-adapter#13]
I have code where I emit before disconnecting the user. However, the User is disconnected before the event is emitted. Is there some kind of `await` thing i could use for emit?

```ts
io.in(opts.to).emit(AUTHENTICATE_ERROR, {
   message: opts.message,
   data: opts.data,
});
io.in(opts.to).disconnectSockets(true);
```

Notes:
• When removing `disconnectSockets`, the `emit` function works.
• When removing this streams adapter, the `emit` + `disconnectSockets` both work perfectly.

**Comment by darrachequesne** [comment]
I could indeed reproduce the issue, I'm digging into this...

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-adapter/commit/a13f35f0e6b85bbba07f99ee2440e914f1429d83, included in `socket.io-adapter@2.5.4` (and thus `@socket.io/redis-streams-adapter@0.2.0`).

Could you please check?

**Comment by SupertigerDev** [comment]
Seems to be fixed, thanks ❤️
