### ISSUE TITLE
Future support of Redis or other BSD license alternatives?

### ISSUE THREAD

**Issue by thanh17** [socketio/socket.io-redis-streams-adapter#22]
With the recent changes in [Redis licensing from BSD-3 to dual RSALv2+SSPLv1](https://github.com/redis/redis/pull/13157), what will the future of ioredis support look like? 

Will this come in the form of transitioning to other forked version of redis like [Valkey](https://github.com/valkey-io)?

**Comment by darrachequesne** [comment]
That's a great question!

I guess that Redis forks like Valkey will try to maintain backward compatibility with Redis, so in the near future I think this adapter should work without any modification.

Let's wait and see.
