### ISSUE TITLE
socket.recovered is not always true

### ISSUE THREAD

**Issue by john-bagatta** [socketio/socket.io-redis-streams-adapter#26]
We have an intermittent test failure around our connection recovery after adding the redis streams adapter to our socket.io system.

The test procedure is:
1. Connect a socket to our server
2. Trigger a reconnection via `socket.io.engine.close()` on the client
3. Wait for the reconnection to occur
4. Check that `socket.recovered` is true

Step 3 reliably occurs, but Step 4 fails approximately 30% of the time. No errors seem to occur in the socket library, it seemingly just doesn't recognize the reconnection as a recovery (or that recovery silently fails). There were no failures using the default in-memory adapter.

**Comment by darrachequesne** [comment]
Hi! I think you should not expect the connection state recovery feature to always succeed, as it won't be the case in production. Successful recovery must really be seen as the happy path.

That being said, there might be two explanations for the recovery failure:

- either the reconnection is too fast (in that case, the server may not have stored the session context in Redis yet)
- or the client is disconnected without having received a first packet (which is necessary to init the offset on the client side)

**Comment by john-bagatta** [comment]
Ah, yeah the test was triggering a reconnect rather quickly - adding a delay seems to have removed the flakiness! Thank you for the suggestion
