### ISSUE TITLE
Request support for Redis Cluster

### ISSUE THREAD

**Issue by seolhw** [socketio/socket.io-redis-streams-adapter#3]

**Comment by MGTechTeam1** [comment]
Bump +1

**Comment by titk12** [comment]
Bump +1

**Comment by giuliopulina** [comment]
Is there any workaround to connect to a cluster of Redis instance within the adapter?

**Comment by darrachequesne** [comment]
It does indeed support connecting to a Redis cluster.

I have added a test to ensure it: https://github.com/socketio/socket.io-redis-streams-adapter/commit/65d0539eb7eb9649845ee744a4de4e0646fa194e

@seolhw @MGTechTeam1 @titk12 could you please check?

**Comment by darrachequesne** [comment]
I've added an example in the README:

```js
import { createCluster } from "redis";
import { Server } from "socket.io";
import { createAdapter } from "@socket.io/redis-streams-adapter";

const redisClient = createCluster({
  rootNodes: [
    {
      url: "redis://localhost:7000",
    },
    {
      url: "redis://localhost:7001",
    },
    {
      url: "redis://localhost:7002",
    },
  ],
});

await redisClient.connect();

const io = new Server({
  adapter: createAdapter(redisClient)
});

io.listen(3000);
```

I think this can be closed now, please reopen if needed.
