### ISSUE TITLE
Handle "Infinity" in maxDisconnectionDuration

### ISSUE THREAD

**Issue by rokkit** [socketio/socket.io-redis-streams-adapter#4]
Passing "Infinty" value into "maxDisconnectionDuration" causes a Redis error:

ERR value is not an integer or out of range.

Because, this value uses as arguments of "PX" in "persistSession" function. 
For example:

`"SET" "sio:session:r-3jx2Zg2y1MlFvcAAAF" "hKNzaWS0a3o4UTRRbWNoY2FhZG1pbnQwa2VupGRhdGGA" "PX" "Infinity"`

**Comment by darrachequesne** [comment]
Hi! I don't think that's a good idea to allow `Infinity`, as it would imply that the sessions can be recovered forever, which is not the case (for example, if the user refreshes its tab, the session is lost, with the current implementation). Do you have a specific use case in mind?

**Comment by darrachequesne** [comment]
I think this can be closed now. Please reopen if needed.
