### ISSUE TITLE
Sometimes the message is not sent.

### ISSUE THREAD

**Issue by hysapp** [socketio/socket.io-redis-streams-adapter#7]
Sometimes a client connects to a cluster and I send it a message. Suddenly, that client disconnects and connects due to Internet failure and connects to another cluster, and there are still messages in the previous cluster that it did not receive. Those messages will never reach him unless he reconnects to the previous cluster. That is, in a chat application, he suddenly receives messages that were sent, for example, an hour ago.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by steveetm** [comment]
We see a very similar issue, no clear repro unfortunately, but if we simply reload the client, sometimes it can receive messages from the server, but most of the time it can't. The websocket is connected, I see ping messages both direction, the client can also send message to the server, which is processed fine, but messages sent to a channel won't arrive on that client. Sometimes it magically fixes itself, without any external action.

We didn't have issues like that before moved to redis-stream-adapter. I was never able to repro it locally, but with normal load on our server it happens a lot(the socket service actually unusable)
